ubuntu:~/projects$ cat dockerfile
# pull a base image which gives all required tools and libraries
FROM openjdk:17-jak-alpine

# create a folder where the app code will be store
WORKDIR /app

# copy the source code from your HOST machine to your container
COPY src/Main.java /app/Main.java 

# compile the application code 
RUN javac src/main.java

# run the application
CMD ["java", "Main"]
